Homework 1 done
Evil-Enot/js-101-2020 pull request #1
Opened 2021-03-23 12:55 UTC by Evil-Enot

2021-04-04 11:57 UTC, DmitryMakhnev requested changes

2021-04-04 11:57 UTC, DmitryMakhnev commented on 08-ts-todo-mvc-react/src/components/main-controls/MainControls.tsx
> +}
Видимо что-то поломалось при переносе, и в дифе я вижу только это. Пожалуйста, поправьте дифф.

2021-04-12 10:57 UTC, Evil-Enot commented on 08-ts-todo-mvc-react/src/components/main-controls/MainControls.tsx
> +}
Исправил PR

2021-05-16 17:34 UTC, DmitryMakhnev approved these changes
👍

2021-05-16 17:49 UTC, merged